[package]
name = "block_hash"
version = "0.1.0"
edition = "2024"

[dependencies]
rlp = "0.5"
tiny-keccak = { version = "2.0", features = ["keccak"] }
ethereum-types = "0.14"
hex = "0.4.3"
sha2 = "0.10.9"
colored = "3.1.1"
